Refactored Router to be a non-static class
tnapf/Router pull request #15
Opened 2023-05-12 08:54 UTC by CommandString

# Why?
In attempts to make all of the libraries in TNAPF comply with PSR and be usable in any circumstance. It only makes sense to convert Router into a non-static class so it can be used with PSR-15. Which will be implemented soon

2023-05-12 10:25 UTC, xHeaven requested changes

2023-05-12 10:25 UTC, xHeaven commented on src/Routing/Route.php
>       */
the phpdoc is incomplete here

2023-05-12 10:25 UTC, xHeaven commented on src/Routing/Route.php
> +    public function __construct(protected readonly Router $router, string $uri, public readonly string $controller, Methods ...$methods)
you should consider breaking down the arguments into newlines to comply with PSR12
eg:
```php
public function __construct(
        protected readonly Router $router,
        string $uri,
        public readonly string $controller,
        Methods ...$methods
    ) {
        // ...
```

2023-05-12 10:25 UTC, xHeaven commented on tests/RouteTests.php
>      public function testRoutePrependsMissingStartingSlash(): void
use `assertSame` instead of `assertEquals` here, as `assertSame` is typesafe

2023-05-12 10:25 UTC, xHeaven commented on tests/RouteTests.php
>      public function testRouteSettingGettingParameters(): void
use `assertSame` instead of `assertEquals` here, as `assertSame` is typesafe

2023-05-13 21:09 UTC, xHeaven requested changes
The changed files are looking good now, but please do a commit with the updated examples as well. Currently, you are calling non-static methods statically in your examples.

2023-05-13 21:11 UTC, CommandString commented
> The changed files are looking good now, but please do a commit with the updated examples as well. Currently, you are calling non-static methods statically in your examples. Update the README too.

Examples are getting nuked and there's gonna be more changes which is why the README hasn't been updated

2023-05-13 21:18 UTC, xHeaven approved these changes
Alright then, sounds good. Approved.

2023-05-13 21:18 UTC, merged